### PR TITLE
Support tui

### PR DESCRIPTION
**Pull request by Grazfather**
This PR lets you:

1. Control using your keyboard
2. Use a super ghetto tui to represent speed.

Basically I almost always run linux in a headless VM and I didn't want to have to bring up a gui just for this.

### CODE REVIEW

**Comment by 1am** [comment]
@zombieCraig Please consider merging this pull request. This could be helpful for other people, myself included

**Comment by 1am** [comment]
@Grazfather Actually tried to compile it with ` make all CFLAGS+=-Wno-error=misleading-indentation CFLAGS+=-DDISABLE_SDL=1` but it throws an error because of extra `}` in the end.

```
controls.c:968:1: error: expected identifier or ‘(’ before ‘}’ token
 }
 ^
<builtin>: recipe for target 'controls.o' failed
make: *** [controls.o] Error 1
```

Removing one of the `}` makes it compile. Is it possible you fix this - otherwise I'd have to make a for of a fork to introduce one cosmetic fix.

**Comment by Grazfather** [comment]
Thanks @1am could you please test building both with and without this setting (which I've done locally) as well as whether the functionality still works?

**Comment by 1am** [comment]
@Grazfather Thanks. Seems to be working ok now in both configurations (with and without `-DDISABLE_SDL=1`)

**Comment by zombieCraig** [comment]
Sorry, I've been traveling a lot and have not had time to test.  I have a question with the removal of lib.o.. Did you write the methods that were in lib.o somewhere.  I'm just doing a manual review at the moment and want to make sure this doesn't break things for others. @Grazfather @1am

**Comment by Grazfather** [comment]
lib.o is built in the Makefile. Doesn't make sense to include binaries in the repo. I personally run it on raspberry pi where the lib.o would be completely invalid.

**Comment by zombieCraig** [comment]
@Grazfather understood.  They binaries were there for students out of convenience, when I teach classes that is the common platform it made it easier than requiring a compiler.  We can remove the binaries and if it becomes an issues I'll just create a separate bin folder or something.  I don't *think* it would be an issue.  Sound good?

**Comment by Grazfather** [comment]
That makes sense. Actually might be easiest for students to build a release, that way they can just download a tar file.

**Comment by Grazfather** [comment]
https://github.com/blog/1547-release-your-software -> This way you can keep the binaries out of the source while still having versions for it.

**Comment by zombieCraig** [comment]
@Grazfather That makes a lot more sense than the way I was doing it.  Thanks for the contributions and I apologize about the delay in merging.

**Comment by zombieCraig** [comment]
@Grazfather fyi, I merged it but the GUI controls is having issues were it segfaults with a bad file descriptor.  I'll dig into it and see if I can track down the issue.

**Comment by Grazfather** [comment]
Hm, I tested that both GUI and TUI work, but that was months ago, maybe I missed something and I forget. I'll test it out today.

**Comment by Grazfather** [comment]
Can you show me a log? I checked out master before your revert and it works fine for me.

**Comment by Grazfather** [comment]
Bad file descriptor was in control.. that makes more sense, that was my parens change, I guess 1am didn't test functionality. Opening new PR with proper fixes.

**Pull request merged**
